
#
# MsgLab by zProgramm
# Version: 1.8.8
#


config:

  prefix: "&a[Bmsg] &8|"
  p-variable: "%c"

  error: "&c[Error] &8|"
  e-variable: "%e"

  # List of enabled commands and options:

  modules:
    enabled-commands:
      - chat
      - bmsg
      - msg
      - reply
      - socialspy
      - broadcast
      - broadcastworld
      - stream
      - ignore
      - unignore
      - helpop
      - staffchat
      - channel
      - motd

    enabled-options:
      - chat_format
      - chat_revisor
      - cooldown
      - join_quit
      - motd

  perms:
    cooldown:
      chat-bypass: bmsg.chat.bypass
      cmd-bypass: bmsg.cmd.bypass

    msg-color: bmsg.msg.color
    chat-color: bmsg.chat.color
    chat-reload: bmsg.chat.reload
    helpop-watch: bmsg.helpop.watch
    revisor-watch: bmsg.revisor.watch
    stream: bmsg.stream
    broadcast: bmsg.broadcast
    broadcast-world: bmsg.broadcast.world
    staff-chat: bmsg.staffchat
    reload: bmsg.reload
    debug: bmsg.debug
    socialspy: bmsg.socialspy
    toggle-admin: bmsg.mtoggle.admin

  metrics: true
  update-check: false
  # If you allow the subcommand to go to the support of the plugin /bmsg support.
  allow-support: true