#
# ChatLab by BryanGaming
# Version: 2.0.3
#

version: 2.0.3

config:

  # List of enabled commands and options:
  modules:
    enabled-commands:
      - chat
      - clab
      - msg
      - reply
      - socialspy
      - broadcast
      - broadcastworld
      - stream
      - ignore
      - unignore
      - helpop
      - staffchat
      - channel
      - motd
      - commandspy
      - announcer
      - party

    enabled-options:
      - chat_format
      - chat_revisor
      - chat_manangent
      - cooldown
      - join_quit
      - motd

#
# Permissions:
# - You can put 'none' to disable the permission.
#

perms:

  # Revisor:
  revisor:
    watch: clab.revisor
    bypass: clab.revisor

  # Cooldown:
  cooldown:
    chat-bypass: clab.chat.bypass
    cmd-bypass: clab.cmd.bypass

  # Commands:
  commands:
    clab:
      main: clab.commands.clab
      debug: clab.commands.clab.debug
      restore: clab.commands.clab.restore
      reload: clab.commands.clab.reload

    broadcast:
      main: clab.commands.broadcast
      click: clab.commands.broadcast.click

    broadcastworld:
      main: clab.commands.broadcast-world
      click: clab.commands.broadcast-world.click

    channel:
      main: none
      info: clab.commands.info
      move: clab.commands.move

    chat:
      main: clab.commands.chat
      reload: clab.commands.chat.reload

    commandspy:
      main: clab.commands.commandspy

    helpop:
      main: clab.commands.helpop
      watch: clab.commands.helpop.watch

    ignore:
      main: none

    motd:
      main: none
      admin: clab.commands.motd.admin

    msg:
      main: none
      toggle: none

    reply:
      main: none

    socialspy:
      main: clab.commands.socialspy

    staffchat:
      main: clab.commands.staffchat
      watch: clab.commands.staffchat

    stream:
      main: clab.commands.stream

    unignore:
      main: none

  # Color:
  color:
    variable: clab.chat.variable

  chat:
    muted-bypass: clab.chat.mute.bypass
  # Chat:

# Options:
options:
  # You can create prefixes with variables unlimited, obiously!
  replacer:

    # Prefix config:
    prefix:
      format: "&b[Clab] &8|"
      variable: "%c"
    # Error config:
    error:
      format: "&c[Error] &8|"
      variable: "%e"


  # You can create tags with variables unlimited, obiously!
  color:

    color:
      variable: "%ml_color%"
      permission: clab.chat.color

    tag:
      variable: "%ml_tag%"
      permission: clab.chat.tag

  metrics: true
  update-check: false

  # To allow hover.
  allow-hover: true
  hover-format: "{%format%}"

  # To use legacy colors:
  use-legacy-colors: true

  # If you allow the subcommand to go to the support of the plugin /clab support.
  allow-support: true