#
# ChatLab by BryanGaming
# Version: 2.0
#

version: 2.0

config:

  # List of enabled commands and options:
  modules:
    enabled-commands:
      - chat
      - clab
      - msg
      - reply
      - socialspy
      - broadcast
      - broadcastworld
      - stream
      - ignore
      - unignore
      - helpop
      - staffchat
      - channel
      - motd
      - commandspy

    enabled-options:
      - chat_format
      - chat_revisor
      - chat_manangent
      - cooldown
      - join_quit
      - motd

#
# Permissions:
# - You can put 'none' to disable the permission.
#

perms:

  # Revisor:
  revisor:
    watch: bmsg.revisor
    bypass: bmsg.revisor

  # Cooldown:
  cooldown:
    chat-bypass: bmsg.chat.bypass
    cmd-bypass: bmsg.cmd.bypass

  # Commands:
  commands:
    bmsg:
      main: bmsg.commands.bmsg
      debug: bmsg.commands.bmsg.debug
      restore: bmsg.commands.bmsg.restore
      reload: bmsg.commands.bmsg.reload

    broadcast:
      main: bmsg.commands.broadcast
      click: bmsg.commands.broadcast.click

    broadcastworld:
      main: bmsg.commands.broadcast-world
      click: bmsg.commands.broadcast-world.click

    channel:
      main: none
      info: bmsg.commands.info
      move: bmsg.commands.move

    chat:
      main: bmsg.commands.chat
      reload: bmsg.commands.chat.reload

    helpop:
      main: bmsg.commands.helpop
      watch: bmsg.commands.helpop.watch

    ignore:
      main: none

    motd:
      main: none
      admin: bmsg.commands.motd.admin

    msg:
      main: none
      toggle: none

    reply:
      main: none

    socialspy:
      main: bmsg.commands.socialspy

    staffchat:
      main: bmsg.commands.staffchat
      watch: bmsg.commands.staffchat

    stream:
      main: bmsg.commands.stream

    unignore:
      main: none

  # Color:
  color:
    variable: bmsg.chat.variable

  chat:
    muted-bypass: bmsg.chat.mute.bypass
  # Chat:

# Options:
options:
  # You can create prefixes with variables unlimited, obiously!
  replacer:

    # Prefix config:
    prefix:
      format: "&a[Bmsg] &8|"
      variable: "%c"
    # Error config:
    error:
      format: "&c[Error] &8|"
      variable: "%e"


  # You can create tags with variables unlimited, obiously!
  color:

    color:
      variable: "%ml_color%"
      permission: bmsg.chat.color

    tag:
      variable: "%ml_tag%"
      permission: bmsg.chat.tag

  metrics: true
  update-check: false

  # To allow hover.
  allow-hover: true
  hover-format: "{%format%}"

  # To use legacy colors:
  use-legacy-colors: true

  # If you allow the subcommand to go to the support of the plugin /bmsg support.
  allow-support: true