#
#   _____ _           _   _           _     
#  / ____| |         | | | |         | |    
# | |    | |__   __ _| |_| |     __ _| |__  
# | |    | '_ \ / _` | __| |    / _` | '_ \ 
# | |____| | | | (_| | |_| |___| (_| | |_) | by BryanGaming
#  \_____|_| |_|\__,_|\__|______\__,_|_.__/  Version: 2.2.4
#
# Main Config | config.yml

#
# File Sectors:
# config.yml = To toggle and configure the commands, modules, messages and permissions.
# messages.yml = To see the command & error messages.
# sounds.yml = To see the sounds manager.
# formats.yml = To see chat formats, etc.
# filters.yml = To see the filters, etc.
# players.yml =To see the data of players.
#

# If you want to go to the wiki: https://app.gitbook.com/@bryangaming/spaces
# Visit the MiniMessage guide: https://docs.adventure.kyori.net/minimessage.html#format
# If you want to go to the support: https://discord.gg/YjhubS3bWW

# Config version, please don't change this path.
config-version: 2.2.4

#
# Options:
#
# General Plugin Configurations
options:
  # You can create prefixes with variables unlimited, obiously!
  # This is not the chat format! If you want to go to formats go to formats.yml.
  replacer:
    # Prefix path:
    prefix:
      # Format path
      format: "<light_purple>[Clab] <dark_gray>|"
      # Variable to be replaced.
      variable: "%c"
    
    # Error path:
    error:
      # Format path
      format: "<red>[Error] <dark_gray>|"
      # Variable to be replaced.
      variable: "%e"
  # Redis! [For bungeecord]:
  redis:
    enabled: false

    # Redis data:
    address: localhost
    port: 25565
    password: add

  # Section to activate or deactivate hooks automatically.
  allow-hooks:
    # Enables the use of money for command-conditions, 
    # the use of prefixes or suffixes in the format, 
    # and for inbound and outbound messages.
    vault: true
    # Enables use of ProtocolLib to handle command autocompletion
    protocollib: true
    # Enable the use of the bot
    discordsrv: true
    # Enables the use of PlaceholderAPI variables in the plugin.
    placeholderapi: true
    # Prevents users in vanish mode from talking,
    # revealing their status on the server.
    # It will also prevent incoming and outgoing messages
    # from being displayed. 
    # This also includes the premium version (PremiumVanish). 
    supervanish: true
    # CMI
    cmi: true

  # Enable metrics
  # You can deactivate it without any problem, 
  # but we recommend that you leave it active, 
  # to show your support to the plugin developers.
  metrics: true
  # Enable update checks.
  # This will announce about a new version to the OPs.
  update-check: false
  # Enable the use of old colors (&).
  # With this option you can make use of the colors,
  # using the & prefix, for example: "&1" and "&2".
  # It is recommended to use MiniMessage over this option,
  # as it is an easier format to understand and handle.
  use-legacy-colors: true
  # If you allow the subcommand to go to the support of the plugin /clab support.
  allow-support: true
  # Allow relational placeholders [Only if you have a faster server].
  allow-relational-placeholders: false


  # Add space limit.
  center-space: 50


# 
# Modules
#
# Plugin modules
modules:
  # Channels Module
  # Here you can configure permissions, channel settings.
  channel:
    # Enable this module?
    enabled: true
    # The default channel the player will be on when logging into the server.
    default-channel: default
    # Permissions of arguments. Put "none" to disable it.
    permissions:
      # main: If player is using the command.
      main: none
      info: clab.commands.info
      move: clab.commands.move


  # Private Messages and Replies module
  # Here you can configure permissions,
  # and the GUI of private messages.
  msg-reply:
    # Enable this module?
    enabled: true
    # Enable rule filters from /msg.
    enable-revisor: true
    # Permissions of arguments. Put "none" to disable it.
    permissions:
      msg:
        # main: If player is using the command /msg.
        main: none
        toggle: none

      reply:
        # main: If player is using the command /reply.
        main: none

    # GUI settings of /msg -online.
    online-gui:
      mode: text

      # Inventory title.
      title: "<green>- <white>Online players <green>[%page%/%max%]"
      player:
        title: "<dark_green>%number%. <green>%playername%"
        lore:
          - ""
          - "<green>-> <white>Click to chat with them!"
      # Icon to go to the next page.
      next-page:
        id_name: "barrier"
        title: "<red>Next page"

        # Not obligatory.
        lore:
          - ""
          - "<white>Click to go to next page."

      previous-page:
        id_name: "diamond"
        title: "<red>Previous page"
        # Not obligatory:
        lore:
          - ""
          - "<white>Click to go to previous page."

  # Broadcast module
  # Configuration of the
  # /broadcast command.
  broadcast:
    # Enable this module?
    enabled: true
    # Permissions of arguments. Put "none" to disable it.
    permissions:
      # Permissions of /broadcast.
      global:
        main: clab.commands.broadcast
        click: clab.commands.broadcast.click
      # Permissions of /broadcastworld.
      world:
        main: clab.commands.broadcast-world
        click: clab.commands.broadcast-world.click

    # Enable rules filters from /broadcast.
    enable-revisor: true

  # Chatting module
  # Configure alternative chat features.
  # To see the chat formats, go to formats.yml
  chat:
    # Enable this module?
    enabled: true

    # Permissions of arguments. Put "none" to disable it.
    permissions:
      # main: If player is using the command.
      main: clab.commands.chat
      reload: clab.commands.chat.reload
      muted-bypass: clab.chat.mute.bypass
    
    # How many empty spaces will be sent to the chat to "clean it up"?
    empty-spaces: 50

  # Main command module
  # Here you can configure all the main plugin command "/clab",
  # as well as its subcommands, permissions and formatting.
  clab:
    # Enable this module?
    enabled: true
    # Permissions of arguments. Put "none" to disable it.
    permissions:
      # main: If player is using the command.
      main: clab.commands.clab
      debug: clab.commands.clab.debug
      restore: clab.commands.clab.restore
      reload: clab.commands.clab.reload

  # Message Of The Day module
  motd:
    # Enable this module?
    enabled: true
    # Permissions of arguments. Put "none" to disable it.
    permissions:
    # main: If player is using the command.
      main: none
      admin: clab.commands.motd.admin


  ignore-unignore:
    # Enable this module?
    enabled: true
    # Permissions of arguments. Put "none" to disable it.
    permissions:
      # main: If player is using the command /ignore or unignore. Put "none" to disable it.
      main: none

  spymodule:
    socialspy:
      # Enable this module?
      enabled: true
      # Permissions of arguments. Put "none" to disable it.
      permissions:
        # main: If player is using the command.
        main: clab.commands.socialspy

    commandspy:
      # Enable this module?
      enabled: true
      # Permissions of arguments. Put "none" to disable it.
      permissions:
        # main: If player is using the command.
        main: clab.commands.commandspy

      # Blocked commands from the commandspy
      blocked-commands:
        - login
        - log
        - register
        - reg

  helpop:
    # Enable this module?
    enabled: true
    # Permissions of arguments. Put "none" to disable it.
    permissions:
      # main: If player is using the command.
      main: clab.commands.helpop
      # Permission for players that can watch the helpop.
      watch: clab.commands.helpop.watch

    # Enable rules filters from /helpop.
    enable-revisor: true

  stream:
    # Enable this module?
    enabled: true
    # Permissions of arguments. Put "none" to disable it.
    permissions:
      # main: If player is using the command.
      main: clab.commands.stream

    # Enable rules filters from /stream.
    enable-revisor: true

    # If you activate this, the streamers can only put a valid link in the text, instead of a welcome text.
    only-link: true
    # Allowed links to say
    allowed-links:
      - www.youtube.com
      - twitch.tv

  staff-chat:
    # Enable this module?
    enabled: true
    # Permissions of arguments. Put "none" to disable it.
    permissions:
      # main: If player is using the command.
      main: clab.commands.staffchat
      # Permission for players that can watch the staffchat.
      watch: clab.commands.staffchat

    # Symbol with which you can start the message to be detected as StaffChat
    symbol: "$"

  announcer:
    # Enable this module?
    enabled: true
    # Global interval in which announcers will be shown
    global-interval: 10
    # Permissions of arguments. Put "none" to disable it.
    permissions:
      # main: If player is using the command.
      main: clab.commands.announcer
    announcers:
      # Type list:
      # Ordered (The messages will be sorted as they are in the messages section).
      # Random (The messages will be aleatory).
      type: ORDERED
      messages:
        1:
          - "<white>Hello!"
        2:
          - "<yellow>Bye!"
        3:
          - "<aqua>ChatLab <yellow>Plugin"
          - "<gray>Author: <rainbow>BryanGaming</rainbow>"


  party:
    # Enable this module?
    enabled: true
    # The limit of players that can enter in party
    max-player-per-party: 10
    # Permissions of arguments. Put "none" to disable it.
    permissions:
      # main: If player is using the command.
      main: none

  chat-format:

    permissions:
      color: clab.chat.color

  tags:
    # Enable this module?
    enabled: true
    permissions:
      # main: If player is using the command.
      main: none

  cooldown:
    # Permissions of arguments. Put "none" to disable it.
    permissions:
      chat-bypass: clab.text.bypass
      cmd-bypass: clab.commands.bypass
