#
# ChatLab by BryanGaming
# Version: 2.1.5
#

version: 2.1.5

# List of enabled commands and options:
modules:
  enabled-commands:
    - chat
    - clab
    - msg
    - reply
    - socialspy
    - broadcast
    - broadcastworld
    - stream
    - ignore
    - unignore
    - helpop
    - staffchat
    - channel
    - motd
    - commandspy
    - announcer
    - party

  enabled-options:
    - chat_format
    - chat_revisor
    - chat_manangent
    - cooldown
    - join_quit
    - motd
    - announcer

# Options:
options:
  # You can create prefixes with variables unlimited, obiously!
  # This is not the chat format! If you want to use the format go to formats.yml.
  replacer:

    # Prefix config:
    prefix:
      format: "&b[Clab] &8|"
      variable: "%c"
    # Error config:
    error:
      format: "&c[Error] &8|"
      variable: "%e"

  allow-hooks:
    vault: true
    protocollib: true
    discordsrv: true
    placeholderapi: true
    supervanish: true

  metrics: true
  update-check: false

  # To allow hover.
  allow-hover: true
  hover-format: "{%format%}"

  # To use legacy colors:
  use-legacy-colors: true

  # If you allow the subcommand to go to the support of the plugin /clab support.
  allow-support: true

