main: me.bryangaming.chatlab.ChatLab
name: ChatLab
version: 2.3.5
author: BryanGaming

loadbefore:
  - EssentialsX

softdepend:
  - AuthMe
  - LockLogin
  - NLogin
  - PlaceholderAPI
  - Vault
  - ProtocolLib
  - DiscordSRV
  - CMI
  - SuperVanish
  - PremiumVanish
  - VanishNoPacket

api-version: 1.13
