main: me.bryangaming.chatlab.ChatLab
name: ChatLab
version: 2.2.4
author: BryanGaming
loadbefore:
  - EssentialsX
softdepend: [ PlaceholderAPI, Multiverse-Core, Vault, ProtocolLib, DiscordSRV, CMI ]
api-version: 1.13
