main: me.bryangaming.chatlab.ChatLab
name: ChatLab
version: 2.3
author: BryanGaming
loadbefore:
  - EssentialsX
softdepend: [LockLogin, PlaceholderAPI, Multiverse-Core, Vault, ProtocolLib, DiscordSRV, CMI ]
api-version: 1.13
