#
# ChatLab by BryanGaming
# Version: 2.2
#

#
# File Sectors:
# config.yml = To toggle the commands and modules or global options.
# commands.yml = To see the all config of commands [messages, perms].
# messages.yml = To see the error messages.
# sounds.yml = To see the sounds manager.
# formats.yml = To see chat formats, etc.
# filters.yml = To see the filters, etc.
# players.yml =To see the data of players.
#

# If you want to go to the wiki: https://app.gitbook.com/@bryangaming/spaces
# Visit the MiniMessage guide: https://docs.adventure.kyori.net/minimessage.html#format
# If you want to go to the support: https://discord.gg/YjhubS3bWW

# Config version, please don't change this path.
config-version: 2.2

#
# Options:
#
options:

  # You can create prefixes with variables unlimited, obiously!
  # This is not the chat format! If you want to go to formats go to formats.yml.
  replacer:

    # Prefix path:
    prefix:
      # Format path
      format: "&b[Clab] &8|"
      # Variable to be replaced.
      variable: "%c"
    
    # Error path:
    error:
      # Format path
      format: "&c[Error] &8|"
      # Variable to be replaced.
      variable: "%e"

  # Section to activate or deactivate hooks automatically.
  allow-hooks:
    vault: true
    # Enables use of ProtocolLib to handle command autocompletion
    protocollib: true
    # Enable the use of the bot
    discordsrv: true
    # Enables the use of PlaceholderAPI variables in the plugin.
    placeholderapi: true
    # Prevents users in vanish mode from talking,
    # revealing their status on the server.
    # It will also prevent incoming and outgoing messages
    # from being displayed. 
    # This also includes the premium version (PremiumVanish). 
    supervanish: true

  # Enable metrics
  # You can deactivate it without any problem, 
  # but we recommend that you leave it active, 
  # to show your support to the plugin developers.
  metrics: true
  # Enable the use of old colors (&).
  # With this option you can make use of the colors,
  # using the & prefix, for example: "&1" and "&2".
  # It is recommended to use MiniMessage over this option,
  # as it is an easier format to understand and handle.
  update-check: false
  # To use legacy colors:
  use-legacy-colors: true
  # If you allow the subcommand to go to the support of the plugin /clab support.
  allow-support: true
